name: Build Java

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "20"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "current"
          arguments: "build"
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Aviz
          path: build/dist/Aviz-1.0-SNAPSHOT.jar
