name: Build Java

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'nightly'
          arguments: 'build'
      - uses: actions/upload-artifact@v3
        with:
          name: Aviz
          path: build/libs/Aviz-1.0-SNAPSHOT.jar
